//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomDKGMonitor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomDKGMonitor.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm sound file not found!.
        /// </summary>
        internal static string strAlarmFileNotFound {
            get {
                return ResourceManager.GetString("strAlarmFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm sound file must be specified!.
        /// </summary>
        internal static string strAlarmFileNotSpecified {
            get {
                return ResourceManager.GetString("strAlarmFileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate value must be number bigger then 0!.
        /// </summary>
        internal static string strBaudRateExc {
            get {
                return ResourceManager.GetString("strBaudRateExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data bits value must be number bigger then 0!.
        /// </summary>
        internal static string strDataBitsExc {
            get {
                return ResourceManager.GetString("strDataBitsExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings.
        /// </summary>
        internal static string strLoadSetExc {
            get {
                return ResourceManager.GetString("strLoadSetExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Period value must be number bigger then 0!.
        /// </summary>
        internal static string strLogPeriodExc {
            get {
                return ResourceManager.GetString("strLogPeriodExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Coolant Temp value must be number!.
        /// </summary>
        internal static string strMaxCoolantTempExc {
            get {
                return ResourceManager.GetString("strMaxCoolantTempExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Coolant Temp value must be number!.
        /// </summary>
        internal static string strMinCoolantTempExc {
            get {
                return ResourceManager.GetString("strMinCoolantTempExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Period value must be number bigger then 0!.
        /// </summary>
        internal static string strNoDataExc {
            get {
                return ResourceManager.GetString("strNoDataExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings.
        /// </summary>
        internal static string strSaveSetExc {
            get {
                return ResourceManager.GetString("strSaveSetExc", resourceCulture);
            }
        }
    }
}
