//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomDKGMonitor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomDKGMonitor.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm DISABLED!.
        /// </summary>
        internal static string strAlarmDisabled {
            get {
                return ResourceManager.GetString("strAlarmDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm ENABLED!.
        /// </summary>
        internal static string strAlarmEnabled {
            get {
                return ResourceManager.GetString("strAlarmEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !ALARM!.
        /// </summary>
        internal static string strAlarmExcl {
            get {
                return ResourceManager.GetString("strAlarmExcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm stopped ringing!.
        /// </summary>
        internal static string strAlarmSoundOff {
            get {
                return ResourceManager.GetString("strAlarmSoundOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm ringing!.
        /// </summary>
        internal static string strAlarmSoundOn {
            get {
                return ResourceManager.GetString("strAlarmSoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm still enabled!.
        /// </summary>
        internal static string strAlarmStillEnabled {
            get {
                return ResourceManager.GetString("strAlarmStillEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomDKGMonitor.
        /// </summary>
        internal static string strAppName {
            get {
                return ResourceManager.GetString("strAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coolant Temp.
        /// </summary>
        internal static string strCoolantTemp {
            get {
                return ResourceManager.GetString("strCoolantTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data flow over port restored.
        /// </summary>
        internal static string strDataFlowRestored {
            get {
                return ResourceManager.GetString("strDataFlowRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Alarm.
        /// </summary>
        internal static string strDisableAlarm {
            get {
                return ResourceManager.GetString("strDisableAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the alarm before stopping the monitoring process!.
        /// </summary>
        internal static string strDisAlarmBeforeStop {
            get {
                return ResourceManager.GetString("strDisAlarmBeforeStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DKG DateTime.
        /// </summary>
        internal static string strDKGDT {
            get {
                return ResourceManager.GetString("strDKGDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Alarm.
        /// </summary>
        internal static string strEnableAlarm {
            get {
                return ResourceManager.GetString("strEnableAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing log file!.
        /// </summary>
        internal static string strErrAccessLog {
            get {
                return ResourceManager.GetString("strErrAccessLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error enumerating serial ports!.
        /// </summary>
        internal static string strErrEnumPorts {
            get {
                return ResourceManager.GetString("strErrEnumPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in settings!.
        /// </summary>
        internal static string strErrInSettings {
            get {
                return ResourceManager.GetString("strErrInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading sound file!.
        /// </summary>
        internal static string strErrLoadSound {
            get {
                return ResourceManager.GetString("strErrLoadSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening port!.
        /// </summary>
        internal static string strErrOpenPort {
            get {
                return ResourceManager.GetString("strErrOpenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index&lt;0..
        /// </summary>
        internal static string strIndexLow0 {
            get {
                return ResourceManager.GetString("strIndexLow0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization error!.
        /// </summary>
        internal static string strInitErr {
            get {
                return ResourceManager.GetString("strInitErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is stopped!.
        /// </summary>
        internal static string strIsStopped {
            get {
                return ResourceManager.GetString("strIsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last data update.
        /// </summary>
        internal static string strLastDataUpd {
            get {
                return ResourceManager.GetString("strLastDataUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you have working serial ports on this machine, or restart your system and try again!.
        /// </summary>
        internal static string strMakeSurePorts {
            get {
                return ResourceManager.GetString("strMakeSurePorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string strNA {
            get {
                return ResourceManager.GetString("strNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data over serial port for.
        /// </summary>
        internal static string strNoDataFor {
            get {
                return ResourceManager.GetString("strNoDataFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is out of limits!.
        /// </summary>
        internal static string strOutLimit {
            get {
                return ResourceManager.GetString("strOutLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing data!.
        /// </summary>
        internal static string strParseErr {
            get {
                return ResourceManager.GetString("strParseErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port closed!.
        /// </summary>
        internal static string strPortClose {
            get {
                return ResourceManager.GetString("strPortClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port opened!.
        /// </summary>
        internal static string strPortOpen {
            get {
                return ResourceManager.GetString("strPortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data receive error..
        /// </summary>
        internal static string strRecieveErr {
            get {
                return ResourceManager.GetString("strRecieveErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is running....
        /// </summary>
        internal static string strRunning {
            get {
                return ResourceManager.GetString("strRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string strSeconds {
            get {
                return ResourceManager.GetString("strSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port is open.
        /// </summary>
        internal static string strSerialIsOpened {
            get {
                return ResourceManager.GetString("strSerialIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port is still open! Do you want to close the port automatically and exit the program?.
        /// </summary>
        internal static string strSerialStillOpen {
            get {
                return ResourceManager.GetString("strSerialStillOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping data with InnerBuffer flush..
        /// </summary>
        internal static string strSkipData {
            get {
                return ResourceManager.GetString("strSkipData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string strStart {
            get {
                return ResourceManager.GetString("strStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started..
        /// </summary>
        internal static string strStarted {
            get {
                return ResourceManager.GetString("strStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string strStop {
            get {
                return ResourceManager.GetString("strStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        internal static string strStopped {
            get {
                return ResourceManager.GetString("strStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try deleting settings file and restarting the program..
        /// </summary>
        internal static string strTryDelSet {
            get {
                return ResourceManager.GetString("strTryDelSet", resourceCulture);
            }
        }
    }
}
